from accounts.models import Question


def load_java_questions():
    questions = [
        {
            "subject": "Java",
            "topic": "Basics",
            "question_type": "MCQ",
            "question": "What is Java?",
            "option1": "A programming language",
            "option2": "A database",
            "option3": "An operating system",
            "option4": "A web browser",
            "answer": "A programming language",
        },
        {
            "subject": "Java",
            "topic": "Basics",
            "question_type": "MCQ",
            "question": "Which company originally developed Java?",
            "option1": "Sun Microsystems",
            "option2": "Microsoft",
            "option3": "Apple",
            "option4": "IBM",
            "answer": "Sun Microsystems",
        },
        {
            "subject": "Java",
            "topic": "Basics",
            "question_type": "MCQ",
            "question": "Which keyword is used to create a class in Java?",
            "option1": "class",
            "option2": "Class",
            "option3": "struct",
            "option4": "new",
            "answer": "class",
        },
        {
            "subject": "Java",
            "topic": "Basics",
            "question_type": "MCQ",
            "question": "Which method is the entry point of a Java program?",
            "option1": "main()",
            "option2": "start()",
            "option3": "run()",
            "option4": "execute()",
            "answer": "main()",
        },
        {
            "subject": "Java",
            "topic": "Basics",
            "question_type": "MCQ",
            "question": "Which keyword is used to inherit a class in Java?",
            "option1": "extends",
            "option2": "implements",
            "option3": "inherits",
            "option4": "super",
            "answer": "extends",
        },
        {
            "subject": "Java",
            "topic": "OOP",
            "question_type": "MCQ",
            "question": "Which of the following is an OOP concept?",
            "option1": "Encapsulation",
            "option2": "Compilation",
            "option3": "Execution",
            "option4": "Debugging",
            "answer": "Encapsulation",
        },
        {
            "subject": "Java",
            "topic": "OOP",
            "question_type": "MCQ",
            "question": "Which OOP concept allows one class to acquire properties of another class?",
            "option1": "Inheritance",
            "option2": "Encapsulation",
            "option3": "Abstraction",
            "option4": "Compilation",
            "answer": "Inheritance",
        },
        {
            "subject": "Java",
            "topic": "OOP",
            "question_type": "MCQ",
            "question": "Which keyword is used to create an object?",
            "option1": "new",
            "option2": "object",
            "option3": "create",
            "option4": "class",
            "answer": "new",
        },
        {
            "subject": "Java",
            "topic": "Data Types",
            "question_type": "MCQ",
            "question": "Which data type is used to store an integer in Java?",
            "option1": "int",
            "option2": "float",
            "option3": "char",
            "option4": "boolean",
            "answer": "int",
        },
        {
            "subject": "Java",
            "topic": "Data Types",
            "question_type": "MCQ",
            "question": "Which data type stores true or false values?",
            "option1": "boolean",
            "option2": "bool",
            "option3": "bit",
            "option4": "logical",
            "answer": "boolean",
        },
        {
            "subject": "Java",
            "topic": "Strings",
            "question_type": "MCQ",
            "question": "Which class is used to represent a string in Java?",
            "option1": "String",
            "option2": "string",
            "option3": "Text",
            "option4": "Character",
            "answer": "String",
        },
        {
            "subject": "Java",
            "topic": "Arrays",
            "question_type": "MCQ",
            "question": "Which property is used to find the length of an array?",
            "option1": "length",
            "option2": "size()",
            "option3": "length()",
            "option4": "count()",
            "answer": "length",
        },
        {
            "subject": "Java",
            "topic": "Exceptions",
            "question_type": "MCQ",
            "question": "Which block is used to handle exceptions?",
            "option1": "try-catch",
            "option2": "if-else",
            "option3": "switch-case",
            "option4": "for-loop",
            "answer": "try-catch",
        },
        {
            "subject": "Java",
            "topic": "Exceptions",
            "question_type": "MCQ",
            "question": "Which keyword is used to manually throw an exception?",
            "option1": "throw",
            "option2": "throws",
            "option3": "exception",
            "option4": "catch",
            "answer": "throw",
        },
        {
            "subject": "Java",
            "topic": "Interfaces",
            "question_type": "MCQ",
            "question": "Which keyword is used when a class implements an interface?",
            "option1": "implements",
            "option2": "extends",
            "option3": "interface",
            "option4": "inherits",
            "answer": "implements",
        },
        {
            "subject": "Java",
            "topic": "Constructors",
            "question_type": "MCQ",
            "question": "What is a constructor in Java?",
            "option1": "A special method used to initialize objects",
            "option2": "A variable",
            "option3": "A package",
            "option4": "An interface",
            "answer": "A special method used to initialize objects",
        },
        {
            "subject": "Java",
            "topic": "Access Modifiers",
            "question_type": "MCQ",
            "question": "Which access modifier makes a member accessible from anywhere?",
            "option1": "public",
            "option2": "private",
            "option3": "protected",
            "option4": "default",
            "answer": "public",
        },
        {
            "subject": "Java",
            "topic": "Collections",
            "question_type": "MCQ",
            "question": "Which collection does not allow duplicate elements?",
            "option1": "Set",
            "option2": "List",
            "option3": "ArrayList",
            "option4": "LinkedList",
            "answer": "Set",
        },
        {
            "subject": "Java",
            "topic": "Packages",
            "question_type": "MCQ",
            "question": "Which keyword is used to define a package?",
            "option1": "package",
            "option2": "import",
            "option3": "namespace",
            "option4": "library",
            "answer": "package",
        },
        {
            "subject": "Java",
            "topic": "JVM",
            "question_type": "MCQ",
            "question": "What does JVM stand for?",
            "option1": "Java Virtual Machine",
            "option2": "Java Variable Machine",
            "option3": "Java Visual Machine",
            "option4": "Java Verified Machine",
            "answer": "Java Virtual Machine",
        },

        # ---------- Java Fill in the Blank ----------

        {
            "subject": "Java",
            "topic": "Basics",
            "question_type": "FILL",
            "question": "Java is a ________ programming language.",
            "answer": "object-oriented",
        },
        {
            "subject": "Java",
            "topic": "Basics",
            "question_type": "FILL",
            "question": "The ________ method is the entry point of a Java program.",
            "answer": "main",
        },
        {
            "subject": "Java",
            "topic": "OOP",
            "question_type": "FILL",
            "question": "The ________ keyword is used to create an object.",
            "answer": "new",
        },
        {
            "subject": "Java",
            "topic": "OOP",
            "question_type": "FILL",
            "question": "The ________ keyword is used for class inheritance.",
            "answer": "extends",
        },
        {
            "subject": "Java",
            "topic": "OOP",
            "question_type": "FILL",
            "question": "Wrapping data and methods into a single unit is called ________.",
            "answer": "Encapsulation",
        },
        {
            "subject": "Java",
            "topic": "Data Types",
            "question_type": "FILL",
            "question": "The ________ data type stores true or false values.",
            "answer": "boolean",
        },
        {
            "subject": "Java",
            "topic": "Strings",
            "question_type": "FILL",
            "question": "The ________ class is used to represent text in Java.",
            "answer": "String",
        },
        {
            "subject": "Java",
            "topic": "Exceptions",
            "question_type": "FILL",
            "question": "Exceptions are commonly handled using ________ and catch blocks.",
            "answer": "try",
        },
        {
            "subject": "Java",
            "topic": "Exceptions",
            "question_type": "FILL",
            "question": "The ________ keyword is used to manually throw an exception.",
            "answer": "throw",
        },
        {
            "subject": "Java",
            "topic": "Interfaces",
            "question_type": "FILL",
            "question": "A class uses the ________ keyword to implement an interface.",
            "answer": "implements",
        },
        {
            "subject": "Java",
            "topic": "Constructors",
            "question_type": "FILL",
            "question": "A constructor is used to ________ an object.",
            "answer": "initialize",
        },
        {
            "subject": "Java",
            "topic": "JVM",
            "question_type": "FILL",
            "question": "JVM stands for Java Virtual ________.",
            "answer": "Machine",
        },
    ]

    for q in questions:
        Question.objects.get_or_create(
            question=q["question"],
            defaults=q
        )
