from accounts.models import Question


def load_ml_questions():
    questions = [
{
            "subject": "Machine Learning",
            "topic": "Introduction",
            "question_type": "MCQ",
            "question": "What is Machine Learning?",
            "option1": "A programming language",
            "option2": "A type of AI",
            "option3": "An operating system",
            "option4": "A database",
            "answer": "A type of AI",
        },
{
            "subject":"Machine Learning",
            "topic":"Introduction",
            "question_type":"MCQ",
            "question":"What is Machine Learning?",
            "option1":"Programming Language",
            "option2":"Artificial Intelligence",
            "option3":"Database",
            "option4":"Operating System",
            "answer":"Artificial Intelligence",
        },
{
            "subject":"Machine Learning",
            "topic":"Introduction",
            "question_type":"MCQ",
            "question":"Machine Learning is a subset of?",
            "option1":"AI",
            "option2":"DBMS",
            "option3":"Networking",
            "option4":"Cloud",
            "answer":"AI",
        },
{
            "subject":"Machine Learning",
            "topic":"Supervised Learning",
            "question_type":"MCQ",
            "question":"Which learning uses labeled data?",
            "option1":"Supervised Learning",
            "option2":"Unsupervised Learning",
            "option3":"Reinforcement Learning",
            "option4":"None",
            "answer":"Supervised Learning",
        },
{
            "subject":"Machine Learning",
            "topic":"Unsupervised Learning",
            "question_type":"MCQ",
            "question":"Which learning uses unlabeled data?",
            "option1":"Supervised Learning",
            "option2":"Unsupervised Learning",
            "option3":"Deep Learning",
            "option4":"Regression",
            "answer":"Unsupervised Learning",
        },
{
            "subject":"Machine Learning",
            "topic":"Algorithms",
            "question_type":"MCQ",
            "question":"Which algorithm is used for classification?",
            "option1":"Decision Tree",
            "option2":"Bubble Sort",
            "option3":"Quick Sort",
            "option4":"Merge Sort",
            "answer":"Decision Tree",
        },
{
            "subject":"Machine Learning",
            "topic":"Regression",
            "question_type":"MCQ",
            "question":"Linear Regression is used for?",
            "option1":"Prediction",
            "option2":"Sorting",
            "option3":"Searching",
            "option4":"Compilation",
            "answer":"Prediction",
        },
{
            "subject":"Machine Learning",
            "topic":"Clustering",
            "question_type":"MCQ",
            "question":"Which algorithm is used for clustering?",
            "option1":"K-Means",
            "option2":"Linear Regression",
            "option3":"Naive Bayes",
            "option4":"SVM",
            "answer":"K-Means",
        },
{
            "subject":"Machine Learning",
            "topic":"Algorithms",
            "question_type":"MCQ",
            "question":"SVM stands for?",
            "option1":"Support Vector Machine",
            "option2":"System Virtual Machine",
            "option3":"Simple Vector Method",
            "option4":"Software Virtual Machine",
            "answer":"Support Vector Machine",
        },
{
            "subject":"Machine Learning",
            "topic":"Evaluation",
            "question_type":"MCQ",
            "question":"Accuracy is used to measure?",
            "option1":"Model Performance",
            "option2":"Database Size",
            "option3":"Memory",
            "option4":"Speed",
            "answer":"Model Performance",
        },
{
            "subject":"Machine Learning",
            "topic":"Deep Learning",
            "question_type":"MCQ",
            "question":"Deep Learning uses?",
            "option1":"Neural Networks",
            "option2":"Stack",
            "option3":"Queue",
            "option4":"Linked List",
            "answer":"Neural Networks",
        },
{
            "subject":"Machine Learning",
            "topic":"Dataset",
            "question_type":"MCQ",
            "question":"Data used to train a model is called?",
            "option1":"Training Data",
            "option2":"Testing Data",
            "option3":"Validation",
            "option4":"Output",
            "answer":"Training Data",
        },
{
            "subject":"Machine Learning",
            "topic":"Dataset",
            "question_type":"MCQ",
            "question":"Data used to evaluate a model is called?",
            "option1":"Testing Data",
            "option2":"Training Data",
            "option3":"Input",
            "option4":"Label",
            "answer":"Testing Data",
        },
{
            "subject":"Machine Learning",
            "topic":"Algorithms",
            "question_type":"MCQ",
            "question":"Which algorithm is used for classification and regression?",
            "option1":"Decision Tree",
            "option2":"K-Means",
            "option3":"Apriori",
            "option4":"PageRank",
            "answer":"Decision Tree",
        },
{
            "subject":"Machine Learning",
            "topic":"Applications",
            "question_type":"MCQ",
            "question":"Machine Learning is used in?",
            "option1":"Recommendation Systems",
            "option2":"Weather Prediction",
            "option3":"Spam Detection",
            "option4":"All of the Above",
            "answer":"All of the Above",
        },
{
            "subject":"Machine Learning",
            "topic":"Applications",
            "question_type":"MCQ",
            "question":"Which company widely uses Machine Learning?",
            "option1":"Google",
            "option2":"Microsoft",
            "option3":"Amazon",
            "option4":"All of the Above",
            "answer":"All of the Above",
        },
{   "subject":"Machine Learning",
            "topic":"Introduction",
"question_type":"FILL",
"question":"Machine Learning is a subset of ________.",
"answer":"Artificial Intelligence",
},
{
"subject":"Machine Learning",
"topic":"Introduction",
"question_type":"FILL",
"question":"The data used to train a model is called ________ data.",
"answer":"Training",
},
{
"subject":"Machine Learning",
"topic":"Introduction",
"question_type":"FILL",
"question":"The data used to test a model is called ________ data.",
"answer":"Testing",
},
{
"subject":"Machine Learning",
"topic":"Supervised Learning",
"question_type":"FILL",
"question":"________ Learning uses labeled data.",
"answer":"Supervised",
},
{
"subject":"Machine Learning",
"topic":"Unsupervised Learning",
"question_type":"FILL",
"question":"________ Learning uses unlabeled data.",
"answer":"Unsupervised",
},
{
"subject":"Machine Learning",
"topic":"Algorithms",
"question_type":"FILL",
"question":"K-Means is a ________ algorithm.",
"answer":"Clustering",
},
{
"subject":"Machine Learning",
"topic":"Algorithms",
"question_type":"FILL",
"question":"SVM stands for Support Vector ________.",
"answer":"Machine",
},
{
"subject":"Machine Learning",
"topic":"Regression",
"question_type":"FILL",
"question":"Linear Regression is used for ________ values.",
"answer":"Predicting",
},
{
"subject":"Machine Learning",
"topic":"Evaluation",
"question_type":"FILL",
"question":"The percentage of correct predictions is called ________.",
"answer":"Accuracy",
},
{
"subject":"Machine Learning",
"topic":"Deep Learning",
"question_type":"FILL",
"question":"Deep Learning mainly uses ________ Networks.",
"answer":"Neural",
},
{
"subject":"Machine Learning",
"topic":"Algorithms",
"question_type":"FILL",
"question":"Decision Tree is mainly used for ________ and regression.",
"answer":"Classification",
},
{
"subject":"Machine Learning",
"topic":"Applications",
"question_type":"FILL",
"question":"Email spam detection is an application of ________ Learning.",
"answer":"Machine",
},
{
"subject":"Machine Learning",
"topic":"Dataset",
"question_type":"FILL",
"question":"The input values of a dataset are called ________.",
"answer":"Features",
},
{
"subject":"Machine Learning",
"topic":"Dataset",
"question_type":"FILL",
"question":"The expected output of a dataset is called the ________.",
"answer":"Label",
},
{
"subject":"Machine Learning",
"topic":"Applications",
"question_type":"FILL",
"question":"Netflix uses Machine Learning for movie ________.",
"answer":"Recommendation",
},
{
"subject":"Machine Learning",
"topic":"Algorithms",
"question_type":"MCQ",
"question":"Which algorithm is used for clustering?",
"option1":"K-Means",
"option2":"Linear Regression",
"option3":"Decision Tree",
"option4":"Naive Bayes",
"answer":"K-Means",
},
{
"subject":"Machine Learning",
"topic":"Algorithms",
"question_type":"MCQ",
"question":"Which algorithm is based on Bayes theorem?",
"option1":"Naive Bayes",
"option2":"KNN",
"option3":"SVM",
"option4":"Random Forest",
"answer":"Naive Bayes",
},
{
"subject":"Machine Learning",
"topic":"Evaluation",
"question_type":"MCQ",
"question":"Which metric measures correct predictions?",
"option1":"Accuracy",
"option2":"Speed",
"option3":"Memory",
"option4":"Bandwidth",
"answer":"Accuracy",
},
{
"subject":"Machine Learning",
"topic":"Algorithms",
"question_type":"MCQ",
"question":"Which algorithm is an ensemble method?",
"option1":"Random Forest",
"option2":"KNN",
"option3":"K-Means",
"option4":"SVM",
"answer":"Random Forest",
},
{
"subject":"Machine Learning",
"topic":"Deep Learning",
"question_type":"MCQ",
"question":"CNN is mainly used for?",
"option1":"Image Processing",
"option2":"Database",
"option3":"Networking",
"option4":"Sorting",
"answer":"Image Processing",
},
{
"subject":"Machine Learning",
"topic":"Deep Learning",
"question_type":"MCQ",
"question":"RNN is mainly used for?",
"option1":"Sequential Data",
"option2":"Sorting",
"option3":"Compression",
"option4":"Searching",
"answer":"Sequential Data",
},
{
"subject":"Machine Learning",
"topic":"Applications",
"question_type":"MCQ",
"question":"Which is an application of Machine Learning?",
"option1":"Spam Detection",
"option2":"Recommendation System",
"option3":"Fraud Detection",
"option4":"All of the Above",
"answer":"All of the Above",
},
{
"subject":"Machine Learning",
"topic":"Evaluation",
"question_type":"MCQ",
"question":"Overfitting means?",
"option1":"Model memorizes training data",
"option2":"Model never trains",
"option3":"Model deletes data",
"option4":"Model compresses files",
"answer":"Model memorizes training data",
},
{
"subject":"Machine Learning",
"topic":"Dataset",
"question_type":"MCQ",
"question":"Which library is widely used for Machine Learning in Python?",
"option1":"Scikit-learn",
"option2":"NumPy",
"option3":"Pandas",
"option4":"All of the Above",
"answer":"Scikit-learn",
},
{
"subject":"Machine Learning",
"topic":"Algorithms",
"question_type":"MCQ",
"question":"Which algorithm is commonly used for classification?",
"option1":"Decision Tree",
"option2":"Bubble Sort",
"option3":"Quick Sort",
"option4":"Merge Sort",
"answer":"Decision Tree",
},
{
"subject":"Machine Learning",
"topic":"Algorithms",
"question_type":"FILL",
"question":"Random Forest is an ________ learning algorithm.",
"answer":"Ensemble",
},
{
"subject":"Machine Learning",
"topic":"Algorithms",
"question_type":"FILL",
"question":"Naive Bayes is based on ________ theorem.",
"answer":"Bayes",
},
{
"subject":"Machine Learning",
"topic":"Evaluation",
"question_type":"FILL",
"question":"A model that performs well on unseen data is said to ________ well.",
"answer":"Generalize",
},
{
"subject":"Machine Learning",
"topic":"Dataset",
"question_type":"FILL",
"question":"The process of cleaning data is called data ________.",
"answer":"Preprocessing",
},
{
"subject":"Machine Learning",
"topic":"Algorithms",
"question_type":"FILL",
"question":"The full form of CNN is Convolutional Neural ________.",
"answer":"Network",
},
{
"subject":"Machine Learning",
"topic":"Algorithms",
"question_type":"FILL",
"question":"The full form of RNN is Recurrent Neural ________.",
"answer":"Network",
},
{
"subject":"Machine Learning",
"topic":"Evaluation",
"question_type":"FILL",
"question":"Overfitting occurs when a model learns the ________ data too well.",
"answer":"Training",
},
{
"subject":"Machine Learning",
"topic":"Evaluation",
"question_type":"FILL",
"question":"The opposite of overfitting is ________.",
"answer":"Underfitting",
},
{
"subject":"Machine Learning",
"topic":"Applications",
"question_type":"FILL",
"question":"Face recognition is an application of ________ Learning.",
"answer":"Machine",
},
{
"subject":"Machine Learning",
"topic":"Applications",
"question_type":"FILL",
"question":"Speech recognition is widely used in virtual ________.",
"answer":"Assistants",
}
    ]

    for q in questions:
        Question.objects.get_or_create(
            question=q["question"],
            defaults=q
        )
