# Generated by Django 5.2.16 on 2026-07-26 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=100)),
                ('question_type', models.CharField(choices=[('MCQ', 'MCQ'), ('FILL', 'Fill in the Blank'), ('TEXT', 'One Line Answer')], max_length=10)),
                ('question', models.TextField()),
                ('option1', models.CharField(blank=True, max_length=200)),
                ('option2', models.CharField(blank=True, max_length=200)),
                ('option3', models.CharField(blank=True, max_length=200)),
                ('option4', models.CharField(blank=True, max_length=200)),
                ('answer', models.CharField(max_length=200)),
            ],
        ),
    ]
