# Generated by Django 5.2.16 on 2026-07-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(choices=[('Python', 'Python'), ('Machine Learning', 'Machine Learning'), ('DBMS', 'DBMS'), ('Java', 'Java')], max_length=50),
        ),
    ]
