# Generated by Django 6.1 on 2026-08-21 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_full_name_student_name_student_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.CharField(default='1', max_length=10),
            preserve_default=False,
        ),
    ]
